/*
 * Protocol codec tests.
 *
 * The C codec is checked against golden vectors generated by
 * tools/proto_ref.py. That Python module is the authoritative definition of
 * the wire format; if these disagree, the C side is wrong.
 *
 * Run on target:
 *   west build -b swifteeg tests/proto && west flash
 */

#include <zephyr/ztest.h>

#include <string.h>

#include "proto.h"
#include "golden_vectors.h"

ZTEST(proto, test_crc_check_value)
{
	/* The standard CRC-16/CCITT-FALSE check value pins the algorithm. */
	zassert_equal(proto_crc16((const uint8_t *)"123456789", 9),
		      GOLDEN_CRC_CHECK,
		      "CRC does not match the CCITT-FALSE check value");
}

ZTEST(proto, test_encode_matches_golden)
{
	uint8_t buf[PROTO_MAX_FRAME];

	for (size_t i = 0; i < GOLDEN_VECTOR_COUNT; i++) {
		const struct golden_vector *v = &golden_vectors[i];

		int n = proto_encode(v->type, v->flags, v->seq,
				     v->payload, v->payload_len,
				     buf, sizeof(buf));

		zassert_equal(n, (int)v->frame_len,
			      "%s: encoded length %d, expected %u",
			      v->name, n, v->frame_len);
		zassert_mem_equal(buf, v->frame, v->frame_len,
				  "%s: encoded bytes differ from reference",
				  v->name);
	}
}

ZTEST(proto, test_decode_matches_golden)
{
	for (size_t i = 0; i < GOLDEN_VECTOR_COUNT; i++) {
		const struct golden_vector *v = &golden_vectors[i];
		proto_frame_t f;

		zassert_equal(proto_decode(v->frame, v->frame_len, &f), PROTO_OK,
			      "%s: decode failed", v->name);
		zassert_equal(f.type, v->type, "%s: type", v->name);
		zassert_equal(f.flags, v->flags, "%s: flags", v->name);
		zassert_equal(f.seq, v->seq, "%s: seq", v->name);
		zassert_equal(f.len, v->payload_len, "%s: len", v->name);

		if (v->payload_len) {
			zassert_mem_equal(f.payload, v->payload, v->payload_len,
					  "%s: payload", v->name);
		}
	}
}

ZTEST(proto, test_decode_rejects_corruption)
{
	/* Every single-byte corruption in a frame must be caught. */
	const struct golden_vector *v = &golden_vectors[3];
	uint8_t buf[PROTO_MAX_FRAME];

	for (uint16_t pos = 0; pos < v->frame_len; pos++) {
		memcpy(buf, v->frame, v->frame_len);
		buf[pos] ^= 0x01;

		proto_frame_t f;
		int err = proto_decode(buf, v->frame_len, &f);

		zassert_not_equal(err, PROTO_OK,
				  "corruption at byte %u went undetected", pos);
	}
}

ZTEST(proto, test_encode_rejects_bad_args)
{
	uint8_t buf[PROTO_MAX_FRAME];
	uint8_t payload[4] = { 1, 2, 3, 4 };

	zassert_equal(proto_encode(0x7F, 0, 0, payload, 4, buf, sizeof(buf)),
		      PROTO_ERR_TYPE, "bad type accepted");
	zassert_equal(proto_encode(PROTO_TYPE_CMD, 0, 0, payload, 4, buf, 4),
		      PROTO_ERR_SPACE, "undersized buffer accepted");
	zassert_equal(proto_encode(PROTO_TYPE_CMD, 0, 0, payload,
				   PROTO_MAX_PAYLOAD + 1, buf, sizeof(buf)),
		      PROTO_ERR_ARG, "oversized payload accepted");
	zassert_equal(proto_encode(PROTO_TYPE_CMD, 0, 0, NULL, 4,
				   buf, sizeof(buf)),
		      PROTO_ERR_ARG, "null payload with nonzero length accepted");
}

ZTEST(proto, test_stream_decodes_back_to_back)
{
	proto_stream_t st;
	proto_frame_t f;
	uint8_t buf[PROTO_MAX_FRAME];

	proto_stream_reset(&st);

	for (size_t i = 0; i < GOLDEN_VECTOR_COUNT; i++) {
		const struct golden_vector *v = &golden_vectors[i];
		bool got = false;

		for (uint16_t b = 0; b < v->frame_len; b++) {
			got = proto_stream_push(&st, v->frame[b], &f);
			/* A frame must only complete on its final byte. */
			if (b < v->frame_len - 1) {
				zassert_false(got, "%s: completed early at %u",
					      v->name, b);
			}
		}

		zassert_true(got, "%s: stream never completed", v->name);
		zassert_equal(f.seq, v->seq, "%s: seq", v->name);
		zassert_equal(f.len, v->payload_len, "%s: len", v->name);
	}

	(void)buf;
	zassert_equal(st.crc_errors, 0, "unexpected CRC errors");
}

ZTEST(proto, test_stream_resyncs_after_garbage)
{
	proto_stream_t st;
	proto_frame_t f;
	const struct golden_vector *v = &golden_vectors[4];

	proto_stream_reset(&st);

	/* Leading noise, including a false SOF, must not prevent recovery. */
	const uint8_t noise[] = { 0x00, 0xFF, 0xA5, 0x99, 0x12, 0xA5, 0x00 };
	for (size_t i = 0; i < sizeof(noise); i++) {
		(void)proto_stream_push(&st, noise[i], &f);
	}

	bool got = false;
	for (uint16_t b = 0; b < v->frame_len; b++) {
		got = proto_stream_push(&st, v->frame[b], &f);
	}

	zassert_true(got, "decoder failed to resync after garbage");
	zassert_equal(f.seq, v->seq, "seq after resync");
	zassert_mem_equal(f.payload, v->payload, v->payload_len,
			  "payload after resync");
}

ZTEST(proto, test_stream_survives_truncated_frame)
{
	proto_stream_t st;
	proto_frame_t f;
	const struct golden_vector *good = &golden_vectors[2];
	const struct golden_vector *cut = &golden_vectors[6];

	proto_stream_reset(&st);

	/*
	 * Half a frame, then good frames.
	 *
	 * The decoder CANNOT know the first frame was truncated until it has
	 * consumed the length that frame declared - so the bytes of the first
	 * good frame are legitimately swallowed making up that count. Only
	 * then does the CRC fail, and only then can it resync. Recovery is
	 * therefore measured as "a later good frame arrives", not "the very
	 * next one does".
	 */
	for (uint16_t b = 0; b < cut->frame_len / 2; b++) {
		(void)proto_stream_push(&st, cut->frame[b], &f);
	}

	bool got = false;
	for (int rep = 0; rep < 3 && !got; rep++) {
		for (uint16_t b = 0; b < good->frame_len; b++) {
			if (proto_stream_push(&st, good->frame[b], &f)) {
				got = true;
			}
		}
	}

	zassert_true(got, "decoder never recovered after a truncated frame");
	zassert_equal(f.seq, good->seq, "seq after truncation");
	zassert_equal(f.len, good->payload_len, "len after truncation");
	zassert_true(st.crc_errors >= 1,
		     "truncated frame should have produced a CRC error");
}

ZTEST(proto, test_stream_poll_drains_buffered_frames)
{
	proto_stream_t st;
	proto_frame_t f;
	const struct golden_vector *v = &golden_vectors[2];

	proto_stream_reset(&st);

	/*
	 * Regression guard. resync() can re-anchor on a SOF with a COMPLETE
	 * frame already behind it; the decoder must parse that immediately
	 * rather than waiting for another byte that may never come.
	 */
	const uint8_t garbage[] = { 0xA5, 0x00, 0x00 };
	for (size_t i = 0; i < sizeof(garbage); i++) {
		(void)proto_stream_push(&st, garbage[i], &f);
	}

	bool got = false;
	for (uint16_t b = 0; b < v->frame_len; b++) {
		if (proto_stream_push(&st, v->frame[b], &f)) {
			got = true;
		}
	}

	zassert_true(got, "frame lost after a false SOF");
	zassert_equal(f.seq, v->seq, "seq wrong after false SOF");

	/* Nothing should remain once the frame has been taken. */
	zassert_false(proto_stream_poll(&st, &f), "poll returned a stale frame");
}

ZTEST_SUITE(proto, NULL, NULL, NULL, NULL, NULL);
